In [31]:
from keras.models import load_model
from keras.preprocessing.image import img_to_array, load_img

BASE_DIR = '../server/'

model = load_model(BASE_DIR + 'models/inception-300.h5')

In [32]:
import json

dog_map = {}
with open(BASE_DIR + 'dog_map.json') as f:
    dog_map = json.load(f)

In [51]:
import os
import numpy as np
from PIL import Image

IMG_SIZE = 300
IMG_PATH = './test/border.jpg'

# Version 1

img = Image.open(IMG_PATH, mode='r')
FILE_NAME = 'dog' + '.' + img.format
img.save(FILE_NAME + '.' + img.format)
img = load_img(FILE_NAME, target_size=(IMG_SIZE, IMG_SIZE))
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
x = x/255
print(x)

os.remove(FILE_NAME)

# Version 2
# img = Image.open(IMG_PATH, mode='r')
# img = img.resize((IMG_SIZE, IMG_SIZE))
# img = img_to_array(img)
# img = np.expand_dims(img, axis=0)
# print(img)

# Array of confidence
prediction = model.predict(x).tolist()[0]

index_array = np.argpartition(prediction, -3)[-3:].tolist()

for index in index_array[::-1]:
    print(prediction[index])
    print(dog_map[str(index)])

# index = np.argmax(prediction)

# print(prediction[0][index])
# print(dog_map[str(index)])

[[[[0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  [[0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  [[0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   [0.8980392  0.9529412  0.99607843]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  ...

  [[0.80784315 0.88235295 0.9411765 ]
   [0.8        0.8745098  0.93333334]
   [0.79607844 0.87058824 0.92941177]
   ...
   [0.44705883 0.5254902  0.61960787]
   [0.42745098 0.50980395 0.58431375]
   [0.5921569  0.6745098  0.7411765 ]]

  [[0.8117647  0.8862745  0.94509804]
   [0.8

'0.000000'