In [1]:
from keras.models import load_model
from keras.preprocessing.image import img_to_array, load_img

BASE_DIR = '../server/'

model = load_model(BASE_DIR + 'models/inception-300.h5')

Using TensorFlow backend.


In [2]:
import json

dog_map = {}
with open(BASE_DIR + 'dog_map.json') as f:
    dog_map = json.load(f)

In [18]:
import os
import numpy as np
from PIL import Image
from keras.applications import imagenet_utils

IMG_SIZE = 300
IMG_PATH = './test/border.jpg'

img = Image.open(IMG_PATH, mode='r')
img = img.resize((IMG_SIZE, IMG_SIZE))
img = img_to_array(img)
img = np.expand_dims(img, axis=0)
img = img/255

print(img)

# Array of confidence
prediction = model.predict(img).tolist()[0]

index_array = np.argpartition(prediction, -3)[-3:].tolist()

for index in index_array[::-1]:
    print(prediction[index])
    print(dog_map[str(index)])

[[[[0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  [[0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  [[0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   [0.8980392  0.9529412  1.        ]
   ...
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]
   [0.8627451  0.9019608  0.9372549 ]]

  ...

  [[0.8039216  0.8784314  0.9372549 ]
   [0.8        0.8745098  0.93333334]
   [0.79607844 0.87058824 0.92941177]
   ...
   [0.42352942 0.52156866 0.60784316]
   [0.41568628 0.5176471  0.58431375]
   [0.5803922  0.68235296 0.73333335]]

  [[0.80784315 0.88235295 0.9411765 ]
   [0.8

'0.000000'